server:
  port: ${BZ_INFOR_INTEGRATION_SERVICE_PORT}

spring:
  application:
    name: bz_infor_integration_service
  profiles:
    active: ${BZ_INFOR_INTEGRATION_SERVICE_SPRING_PROFILES_ACTIVE}
  datasource:
    url: jdbc:sqlserver://${BZ_INFOR_INTEGRATION_SERVICE_DB_HOST}:${BZ_INFOR_INTEGRATION_SERVICE_DB_PORT};database=${BZ_INFOR_INTEGRATION_SERVICE_DB_NAME};encrypt=false;trustServerCertificate=true
    username: ${BZ_INFOR_INTEGRATION_SERVICE_DB_USER}
    password: ${BZ_INFOR_INTEGRATION_SERVICE_DB_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
  rabbitmq:
    host: ${BZ_INFOR_INTEGRATION_SERVICE_RABBITMQ_HOST}
    port: ${BZ_INFOR_INTEGRATION_SERVICE_RABBITMQ_PORT}
    username: ${BZ_INFOR_INTEGRATION_SERVICE_RABBITMQ_USER}
    password: ${BZ_INFOR_INTEGRATION_SERVICE_RABBITMQ_PASSWORD}

logging:
  config: classpath:logging/logback-spring.xml
  level:
    root: INFO
    ru.bz.bzinforintegrationservice: ${BZ_INFOR_INTEGRATION_SERVICE_LOGGING_LEVEL}
    org.springframework.amqp: WARN
    org.springframework.amqp.rabbit.core.RabbitTemplate: WARN
    org.hibernate.SQL: WARN

# Actuator
management:
  server:
    port: ${BZ_INFOR_INTEGRATION_SERVICE_ACTUATOR_PORT}
  endpoints:
    web:
      exposure:
        include: "health,info,loggers,metrics"
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
      probes:
        enabled: true  # For /actuator/health/liveness and /actuator/health/readiness
  info:
    env:
      enabled: true
  health:
    db:
      enabled: true
    rabbit:
      enabled: true
    diskspace:
      enabled: false
info:
  app:
    description: Integration service with Infor LN
  environment: ${BZ_INFOR_INTEGRATION_SERVICE_SPRING_PROFILES_ACTIVE:local}


application:
  mssql:
    infor_company: 302
#    infor_company: ${BZ_INFOR_INTEGRATION_SERVICE_DB_INFOR_COMPANY}
  token:
    signing:
      key: ${BZ_INFOR_INTEGRATION_SERVICE_JWT_KEY}
  rabbitmq:
    exchange:
      measured_remainders_direct: ${RABBIT_EXCHANGE_MEASURED_REMAINDERS_DIRECT}
      warehouse_direct: ${RABBIT_EXCHANGE_WAREHOUSE_DIRECT}
      barcode_direct: ${RABBIT_EXCHANGE_BARCODE_DIRECT}
      mechanicalpart_direct: ${RABBIT_EXCHANGE_MECHANICALPART_DIRECT}
    queue:
      find_measured_remainders: ${RABBIT_QUEUE_FIND_MEASURED_REMAINDERS}
      update_measured_remainder: ${RABBIT_QUEUE_UPDATE_MEASURED_REMAINDER}
      inventory_measured_remainders: ${RABBIT_QUEUE_INVENTORY_MEASURED_REMAINDERS}
      find_stock_list: ${RABBIT_QUEUE_FIND_STOCK_LIST}
      get_item_detail: ${RABBIT_QUEUE_GET_ITEM_DETAIL}
      get_lot_detail: ${RABBIT_QUEUE_GET_LOT_DETAIL}
      get_warehouse_detail: ${RABBIT_QUEUE_GET_WAREHOUSE_DETAIL}
      get_location_detail: ${RABBIT_QUEUE_GET_LOCATION_DETAIL}
      get_container: ${RABBIT_QUEUE_GET_CONTAINER}
      find_containers: ${RABBIT_QUEUE_FIND_CONTAINERS}
      find_barcode_data: ${RABBIT_QUEUE_FIND_BARCODE_DATA}
      report_operation: ${RABBIT_QUEUE_REPORT_OPERATION}
    key:
      find_measured_remainders: ${RABBIT_KEY_FIND_MEASURED_REMAINDERS}
      update_measured_remainder: ${RABBIT_KEY_UPDATE_MEASURED_REMAINDER}
      inventory_measured_remainders: ${RABBIT_KEY_INVENTORY_MEASURED_REMAINDERS}
      find_stock_list: ${RABBIT_KEY_FIND_STOCK_LIST}
      get_item_detail: ${RABBIT_KEY_GET_ITEM_DETAIL}
      get_lot_detail: ${RABBIT_KEY_GET_LOT_DETAIL}
      get_warehouse_detail: ${RABBIT_KEY_GET_WAREHOUSE_DETAIL}
      get_location_detail: ${RABBIT_KEY_GET_LOCATION_DETAIL}
      get_container: ${RABBIT_KEY_GET_CONTAINER}
      find_containers: ${RABBIT_KEY_FIND_CONTAINERS}
      find_barcode_data: ${RABBIT_KEY_FIND_BARCODE_DATA}
      report_operation: ${RABBIT_KEY_REPORT_OPERATION}