package ru.bz.bzinforintegrationservice.infrastructure.persistence.mssql

import org.springframework.stereotype.Component

@Component
object EntityFieldsProvider {
    const val ID = "id"
    const val CODE = "code"
    const val DESCRIPTION = "description"
    const val REMAINDER = "remainder"
    const val PROJECT = "project"
    const val PROJECT_CODE = "project_code"
    const val EFFECTIVITY_UNIT = "effectivity_unit"
    const val EFFECTIVITY_UNIT_CODE = "effectivity_unit_code"
    const val MATERIAL = "material"
    const val WAREHOUSE_ORDER_ORIGIN = "warehouse_order_origin"
    const val WAREHOUSE_ORDER_CODE = "warehouse_order_code"
    const val WAREHOUSE_ORDER_SET = "warehouse_order_set"
    const val WAREHOUSE_ORDER_LINE = "warehouse_order_line"
    const val WAREHOUSE_ORDER_SEQUENCE = "warehouse_order_sequence"
    const val WAREHOUSE = "warehouse"
    const val WAREHOUSE_CODE = "warehouse_code"
    const val WAREHOUSE_DESC = "warehouse_desc"
    const val WAREHOUSE_OWNER_CODE = "warehouse_owner_code"
    const val BIN_CODE = "bin_code"
    const val BIN_DESC = "bin_desc"
    const val LOCATION = "location"
    const val LOCATION_CODE = "location_code"
    const val LOCATION_DESC = "location_desc"
    const val ITEM = "item"
    const val ITEM_CODE = "item_code"
    const val ITEM_DESC = "item_desc"
    const val UNIT_CODE = "unit_code"
    const val UNIT_DESC = "unit_desc"
    const val SEQUENCE = "sequence"
    const val CONTAINER_WAREHOUSE_CODE = "container_warehouse_code"
    const val CONTAINER_BIN_CODE = "container_bin_code"
    const val STATUS = "status"
    const val STATUS_CODE = "status_code"
    const val COMMENT = "comment"
    const val LENGTH = "length"
    const val WIDTH = "width"
    const val DEPTH = "depth"
    const val THICKNESS = "thickness"
    const val LOT = "lot"
    const val LOT_CODE_ORIGINAL = "lot_code_original"
    const val LOT_CODE_FINAL = "lot_code_final"
    const val LOT_CODE = "lot_code"
    const val LOT_CODE_PARENT = "lot_code_parent"
    const val LOT_CODE_SOURCE = "lot_code_source"
    const val QUANTITY = "quantity"
    const val QUANTITY_AVAILABLE = "quantity_available"
    const val QUANTITY_BLOCKED = "quantity_blocked"
    const val QUANTITY_ALLOCATED = "quantity_allocated"
    const val USER_LOGIN_LAST_MODIFIED = "user_login_last_modified"
    const val LINE = "line"
    const val ORDER = "order"
    const val SET = "set"
    const val DATE_LAST_MODIFIED = "date_last_modified"
    const val PAGE = "page"
    const val PAGE_SIZE = "page_size"
    const val DATA = "data"
    const val JSON_DATA = "json_data"
    const val INVENTORY_DATE = "inventory_date"
}